### ISSUE TITLE
Edit user profile page

### ISSUE THREAD

**Issue by ThadeuLuz** [ThadeuLuz/redfire-boilerplate#18]
Create a page to edit the user profile with:

- Change name (both ours and [users profile](https://firebase.google.com/docs/auth/web/manage-users#update_a_users_profile))
- [Change email](https://firebase.google.com/docs/auth/web/manage-users#set_a_users_email_address)
- [Delete Account](https://firebase.google.com/docs/auth/web/manage-users#delete_a_user)

**Comment by douglasppaz** [comment]
#20
